In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  3.8010e-29],
        [-1.5846e+29,  1.4569e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28],
        [ 1.4603e-19,  1.0899e+27,  6.8943e+34],
        [ 1.1835e+22,  7.0976e+22,  1.8515e+28]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.9667, 0.6212, 0.7167],
        [0.7484, 0.2213, 0.4574],
        [0.5287, 0.0183, 0.8593],
        [0.7228, 0.5990, 0.4457],
        [0.6974, 0.3261, 0.0192]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = x.new_zeros(5, 3, dtype=torch.double)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.8484, -1.3320,  0.6018],
        [-1.5312,  0.5357, -1.2285],
        [-1.3612,  0.5963,  0.6489],
        [ 0.0607, -0.2632, -0.7087],
        [-0.3319, -0.9360, -1.8732]])


In [12]:
y = torch.rand(5,3)

In [13]:
print(x + y)

tensor([[ 1.7251, -0.3887,  0.7258],
        [-0.6577,  0.7134, -0.7355],
        [-1.2394,  1.3995,  1.0030],
        [ 0.3093, -0.1191, -0.5141],
        [ 0.3346, -0.8004, -1.6448]])


In [14]:
result = torch.empty(5,3)

In [15]:
torch.add(x,y, out=result)

tensor([[ 1.7251, -0.3887,  0.7258],
        [-0.6577,  0.7134, -0.7355],
        [-1.2394,  1.3995,  1.0030],
        [ 0.3093, -0.1191, -0.5141],
        [ 0.3346, -0.8004, -1.6448]])

In [16]:
result

tensor([[ 1.7251, -0.3887,  0.7258],
        [-0.6577,  0.7134, -0.7355],
        [-1.2394,  1.3995,  1.0030],
        [ 0.3093, -0.1191, -0.5141],
        [ 0.3346, -0.8004, -1.6448]])

In [17]:
y.add_(x)

tensor([[ 1.7251, -0.3887,  0.7258],
        [-0.6577,  0.7134, -0.7355],
        [-1.2394,  1.3995,  1.0030],
        [ 0.3093, -0.1191, -0.5141],
        [ 0.3346, -0.8004, -1.6448]])

In [18]:
x

tensor([[ 0.8484, -1.3320,  0.6018],
        [-1.5312,  0.5357, -1.2285],
        [-1.3612,  0.5963,  0.6489],
        [ 0.0607, -0.2632, -0.7087],
        [-0.3319, -0.9360, -1.8732]])

In [19]:
x[:, 1]

tensor([-1.3320,  0.5357,  0.5963, -0.2632, -0.9360])

In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2610])
0.26098260283470154


In [22]:
a = torch.ones(5)

In [23]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [26]:
print(b)

[2. 2. 2. 2. 2.]


In [27]:
import numpy as np

In [28]:
a = np.ones(5)

In [29]:
b = torch.from_numpy(a)

In [30]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [31]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [32]:
x = torch.ones(2, 2, requires_grad=True)

In [33]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)